ContentExplorer/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using ContentExplorer.Models;
using ContentExplorer.Services;

namespace ContentExplorer.Controllers
{
    public class ImageController : Controller
    {
        [HttpGet]
        public ActionResult Index(string path = "", int? page = 1, string filter = null)
        {
            if (page == null || page < 1)
            {
                page = 1;
            }

            if (path == null)
            {
                path = "";
            }
            else
            {
                // Remove any dangerous characters to prevent escaping the current context
                path = path.Trim("/\\.".ToCharArray());
            }

            if (filter == null)
            {
                filter = "";
            }

            DirectoryInfo directoryInfo = GetCurrentDirectory(path);

            if (directoryInfo.Exists == false)
            {
                return RedirectToAction("Index", new { page, filter });
            }

            ViewBag.FilesPerPage = 50;
            ViewBag.Directory = directoryInfo;
            ViewBag.Page = page;
            ViewBag.Filter = filter;

            return View();
        }

        [HttpGet]
        public ActionResult ReformatNames(string path = "")
        {
            DirectoryInfo baseDirectory = GetCurrentDirectory(path);
            IEnumerable<FileInfo> subFiles = baseDirectory.EnumerateFiles("*", SearchOption.AllDirectories);
            NameFormatService nameFormatService = new NameFormatService();
            string cdnDiskLocation = ConfigurationManager.AppSettings["BaseDirectory"];

            foreach (FileInfo subFile in subFiles)
            {
                FileInfo newFileName = nameFormatService.FormatFileName(subFile);

                if (subFile.Name.Equals(newFileName.Name, StringComparison.OrdinalIgnoreCase) != true)
                {
                    ICollection<TagLink> tagLinksForFile = TagLink.GetByFileName(subFile.FullName);

                    foreach (TagLink tagLink in tagLinksForFile)
                    {
                        tagLink.FilePath = newFileName.FullName.Substring(cdnDiskLocation.Length + 1);
                        tagLink.Update();
                    }
                }
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult RebuildThumbnails(string path = "")
        {
            IThumbnailService imageThumbnailService = new ImageThumbnailService();

            DirectoryInfo baseDirectory = GetCurrentDirectory(path);
            IEnumerable<FileInfo> images = baseDirectory.EnumerateFiles("*", SearchOption.AllDirectories)
                .Where(image => imageThumbnailService.IsThumbnail(image) != true);
            foreach (FileInfo image in images)
            {
                imageThumbnailService.DeleteThumbnailIfExists(image);
                imageThumbnailService.CreateThumbnail(image);
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ViewResult View(string path, int page, string filter = "")
        {
            if (page < 1)
            {
                page = 1;
            }

            if (filter == null)
            {
                filter = "";
            }

            ViewBag.Path = path;
            ViewBag.Id = page;
            ViewBag.Filter = filter;

            return View();
        }

        private DirectoryInfo GetCurrentDirectory(string relativePath)
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(Path.Combine(ConfigurationManager.AppSettings["BaseDirectory"], ConfigurationManager.AppSettings["ImagesPath"], relativePath));

            return directoryInfo;
        }
    }
}

ContentExplorer/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using ContentExplorer.Models;
using ContentExplorer.Services;

namespace ContentExplorer.Controllers
{
    public class VideoController : Controller
    {
        [HttpGet]
        public ActionResult Index(string path = "", int? page = 1, string filter = null)
        {
            if (page == null || page < 1)
            {
                page = 1;
            }

            if (path == null)
            {
                path = "";
            }
            else
            {
                // Remove any dangerous characters to prevent escaping the current context
                path = path.Trim("/\\.".ToCharArray());
            }

            if (filter == null)
            {
                filter = "";
            }

            DirectoryInfo directoryInfo = GetCurrentDirectory(path);

            if (directoryInfo.Exists == false)
            {
                return RedirectToAction("Index", new { page, filter });
            }

            ViewBag.FilesPerPage = 50;
            ViewBag.Directory = directoryInfo;
            ViewBag.Page = page;
            ViewBag.Filter = filter;

            return View();
        }

        [HttpGet]
        public ViewResult View(string path, int page, string filter = "")
        {
            if (page < 1)
            {
                page = 1;
            }

            if (filter == null)
            {
                filter = "";
            }
            ViewBag.Path = path;
            ViewBag.Id = page;
            ViewBag.Filter = filter;

            // Zero-based index
            int pageIndex = page - 1;

            int startingPreview = pageIndex - 7 < 1 ? 1 : page - 7;
            ViewBag.StartingPreview = startingPreview;

            return View();
        }

        [HttpGet]
        public ActionResult RebuildThumbnails(string path = "")
        {
            IThumbnailService videoThumbnailService = new VideoThumbnailService();

            DirectoryInfo baseDirectory = GetCurrentDirectory(path);
            IEnumerable<FileInfo> videos = baseDirectory.EnumerateFiles("*", SearchOption.AllDirectories)
                .Where(image => videoThumbnailService.IsThumbnail(image) != true);

            foreach (FileInfo video in videos)
            {
                videoThumbnailService.DeleteThumbnailIfExists(video);
                videoThumbnailService.CreateThumbnail(video);
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ReformatNames(string path = "")
        {
            DirectoryInfo baseDirectory = GetCurrentDirectory(path);

            ReformatNames(baseDirectory);

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ConvertUnplayableVideos(string path = "")
        {
            DirectoryInfo baseDirectory = GetCurrentDirectory(path);
            VideoConversionService videoConversionService = new VideoConversionService();

            videoConversionService.ConvertUnplayableVideos(baseDirectory);

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private ActionResult ReformatNames(DirectoryInfo directory)
        {
            IEnumerable<DirectoryInfo> subDirectories = directory.GetDirectories();

            foreach (DirectoryInfo subDirectory in subDirectories)
            {
                ReformatNames(subDirectory);
            }

            NameFormatService nameFormatService = new NameFormatService();
            IEnumerable<FileInfo> videos = directory.EnumerateFiles("*", SearchOption.AllDirectories);
            foreach (FileInfo video in videos)
            {
                nameFormatService.FormatFileName(video);
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private DirectoryInfo GetCurrentDirectory(string relativePath)
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(Path.Combine(ConfigurationManager.AppSettings["BaseDirectory"], ConfigurationManager.AppSettings["VideosPath"], relativePath));

            return directoryInfo;
        }
    }
}

ContentExplorer/Views/Shared/_Index.cshtml
@{
    string cdn = ConfigurationManager.AppSettings["CDNPath"];
    DirectoryInfo currentDirectory = ViewBag.Directory;
    string baseSiteDirectory = ConfigurationManager.AppSettings["BaseDirectory"];
    string path = currentDirectory.FullName.Substring(baseSiteDirectory.Length + ViewBag.BaseDirectory.Length + 1).Trim("\\/.".ToCharArray());
    int filesPerPage = ViewBag.FilesPerPage;
    Layout = "./_Layout.cshtml";
}

@using System.Configuration

<li class="directory_item" data-template="directory" style="display: none; background-size: cover; background-position: center center">
    <a href="" class="directory_link"></a>
    <label class="media_name">
        <input type="checkbox" data-tag-selector data-tag-type="directory" data-template />
        <span data-directory-name></span>
    </label>
</li>

<li class="media_item" data-template="file" style="display: none; background-size: cover">
    <a href="" class="media_link"></a>
    <label class="media_name">
        <input type="checkbox" data-tag-selector data-tag-type="file" data-template />
        <span data-file-name></span>
    </label>
</li>

<input type="hidden" value="@ViewBag.Filter" name="Filter" />
<input type="hidden" value="@ViewBag.Page" name="Page" />
<input type="hidden" value="@ViewBag.FilesPerPage" name="FilesPerPage" />
<input type="hidden" value="@ConfigurationManager.AppSettings["CDNPath"]" name="CdnPath" />
<input type="hidden" value="@(path)" name="Path" />

<nav data-stepping-stones class="steppingstone_list"></nav>

<div class="sidebar">

    <h2>Filters</h2>

    <div data-filter>
        <label class="input-group" for="txtFilter">
            Custom filter
            <input type="text" id="txtFilter" value="@ViewBag.Filter" class="input-sm" data-custom-filter />
            <button style="@(ViewBag.Filter != "" ? "display: inline-block" : "display: none")" data-clear-filter>X</button>
        </label>
        <button class="btn btn-default" data-apply-filter>Apply Custom Filter</button>
    </div>

    <div data-tagging>
        <ul class="tagList" data-tags-for-folder></ul>
        <h2>Add Tags</h2>
        <label class="input-group">
            Tag Names
            <input class="input-sm" type="text" data-tag-name autocomplete="off" data-lpignore="true" data-form-type="text" />
        </label>
        <button class="btn btn-default" data-add-tag>Add Tags</button>
    </div>

</div>
<div class="content_sidebar panel">

    @RenderSection("BeforeContent", false)

    <div class="btn-block" data-media-selection></div>

    <section style="display: none" data-directories>
        <h1>Directories</h1>
        <ul class="directory_list" data-directory-list></ul>
    </section>

    <section style="display: none" data-files>
        <h1>Files</h1>
        <ul class="media_list" data-file-list></ul>
    </section>

    <div class="btn-block" data-media-selection></div>

    <div style="display: none" class="button_wrapper" data-pages>
        <div class="button_list" data-page-list></div>
        <div data-total-pages></div>
    </div>

    <input type="hidden" name="FilesPerPage" value="@filesPerPage" />
</div>

@RenderBody()

@section scripts {

    @RenderSection("scripts", required: false)
}

ContentExplorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | ContentExplorer</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()

    @Scripts.Render("~/bundles/scripts/common")
    @RenderSection("scripts", required: false)
</body>
</html>

ContentExplorer/Views/Shared/_View.cshtml
@{
    string cdn = ConfigurationManager.AppSettings["CDNPath"];
    string baseSiteDirectory = ConfigurationManager.AppSettings["BaseDirectory"];

    Layout = "./_Layout.cshtml";
}

@using System.Configuration
@using System.Web.UI.WebControls

<input type="hidden" value="@baseSiteDirectory" data-site-base-directory autocomplete="off" />
<input type="hidden" value="@cdn" data-cdn-path autocomplete="off" />
<input type="hidden" value="@ViewBag.Path" data-relative-directory autocomplete="off" />
<input type="hidden" value="@ViewBag.Filter" data-filter autocomplete="off" />
<input type="hidden" value="@ViewBag.StartingPreview" data-starting-preview autocomplete="off" />

<nav class="steppingstone_list" data-stepping-stones></nav>

@RenderSection("BeforeContent", false)

@RenderSection("MediaView")


<div class="button_wrapper" data-page-button-wrapper style="display: none">
    <div class="button_list" data-page-button-list></div>
    <div>
        <b data-current-page>@ViewBag.Id</b> of <span data-max-pages></span>
    </div>
    <div class="controls" data-controls>
        @RenderSection("Controls", false)
    </div>
</div>

<div data-tags>
    <ul data-tag-list></ul>
</div>

@RenderBody()

@section scripts {

    @RenderSection("scripts", required: false)
}